version: '3.8'

volumes:
  mariadb-data:
  mariadb-old-data:
  mysql-data:
  percona-data:

services:

  mariadb:
    image: mariadb:10.11
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
    ports:
      - "3000:3306"

  mariadb-old:
    image: mariadb:10.6
    volumes:
      - mariadb-old-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
    ports:
      - "3001:3306"

  mysql:
    image: mysql:8
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
    ports:
      - "3002:3306"

  percona:
    image: percona:8
    volumes:
      - percona-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
    ports:
      - "3003:3306"